# Generated by Django 4.0 on 2022-09-28 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('diameter', models.DecimalField(choices=[(1.75, 'One Seven Five'), (2.85, 'Two Eight Five')], decimal_places=2, default=1.75, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Hotend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nozzle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=255)),
                ('diameter', models.DecimalField(decimal_places=2, default=0.4, max_digits=3)),
                ('notes', models.TextField(blank=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tip_params.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ToolchangeParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toolchange_temperature', models.IntegerField(default=0)),
                ('string_reduction_enable_skinnydip', models.BooleanField(default=False)),
                ('string_reduction_insertion_distance', models.DecimalField(decimal_places=2, default=31, max_digits=5)),
                ('string_reduction_pause_in_melt_zone', models.IntegerField(default=0)),
                ('string_reduction_pause_before_extraction', models.IntegerField(default=0)),
                ('string_reduction_speed_to_move_into_melt_zone', models.DecimalField(decimal_places=2, default=33, max_digits=5)),
                ('string_reduction_speed_to_extract_from_melt_zone', models.DecimalField(decimal_places=2, default=70, max_digits=5)),
                ('minimal_purge_on_wipe_tower', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('max_speed_on_the_wipe_tower', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('loading_speed_at_start', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('loading_speed', models.DecimalField(decimal_places=2, default=28, max_digits=5)),
                ('unloading_speed_at_start', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('unloading_speed', models.DecimalField(decimal_places=2, default=90, max_digits=5)),
                ('filament_load_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('filament_unload_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('delay_after_unloading', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('number_of_cooling_moves', models.DecimalField(decimal_places=2, default=4, max_digits=5)),
                ('speed_of_the_first_cooling_move', models.DecimalField(decimal_places=2, default=2.2, max_digits=5)),
                ('speed_of_the_last_cooling_move', models.DecimalField(decimal_places=2, default=3.4, max_digits=5)),
                ('pigment_percentage', models.DecimalField(decimal_places=2, default=0.5, max_digits=5)),
                ('total_ramming_time', models.DecimalField(decimal_places=2, default=2.5, max_digits=5)),
                ('ramming_line_width', models.DecimalField(decimal_places=2, default=1.2, max_digits=5)),
                ('ramming_line_spacing', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('ramming_parameters', models.TextField(blank=True)),
                ('filament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tip_params.filament')),
                ('hotend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tip_params.hotend')),
                ('nozzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tip_params.nozzle')),
            ],
        ),
        migrations.AddField(
            model_name='hotend',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tip_params.manufacturer'),
        ),
        migrations.AddField(
            model_name='filament',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tip_params.manufacturer'),
        ),
    ]
